algoritmo "Negativo_ou_positivo"
// Função : Faça um Programa que peça um valor
//          e mostre na tela se o valor é positivo ou negativo.
// Autor : Iasmim Cunha
// Data : 5/8/2013
// Seção de Declarações 
var
  primeiro: inteiro
inicio
// Seção de Comandos
escreval("Entre com o primeiro valor...")
leia(primeiro)
   se(primeiro < 0) entao
       escreval("O número é negativo")
   senao
       escreval("O número é positivo")
   fimse
fimalgoritmo
