algoritmo "Transforma_FC"
// Função :   Faça um Programa que peça a temperatura
//            em graus Farenheit, transforme e mostre
//            a temperatura em graus Celsius.
// Autor : Iasmim Cunha
// Data : 5/8/2013
// Seção de Declarações 
var
celsius : real
farenheit : real
inicio
// Seção de Comandos
escreval("Entre com o valor da temperatura em Graus Farenheit")
leia(farenheit)
celsius <- (5 * (farenheit-32) / 9)
escreval("O valor  ",Farenheit," em Farenheit,equivale a ",celsius," em graus Celsius ")
fimalgoritmo
