algoritmo "Dobro_quadrado"
// Função :Faça um Programa que calcule a área de um quadrado
//        , em seguida mostre o dobro desta área para o usuário.
// Autor : Iasmim Cunha
// Data : 5/8/2013
// Seção de Declarações 
var
lado :real
area :real
inicio
// Seção de Comandos 
escreval("Entre com o valor da lado do quadrado")
leia(lado)
area <- lado * lado
escreval("O Dobro da área do quadrado é",2*area)

fimalgoritmo
