algoritmo "Transforma_cf"
// Função :Faça um Programa que peça
//         a temperatura em graus Celsius
//         , transforme e mostre em graus Farenheit
// Autor : Iasmim Cunha
// Data : 5/8/2013
// Seção de Declarações 
var
celsius : real
farenheit : real
inicio
// Seção de Comandos
escreval("Entre com o valor da temperatura em Graus Celsius")
leia(celsius)
farenheit <- (celsius*9/5) +32
escreval("O valor  ",celsius," em Celsius,equivale a ",farenheit," em graus Farenheit ")
fimalgoritmo
fimalgoritmo
